baseURL: 'https://www.seusite.com/'
languageCode: 'pt-br'
title: 'Título da Página | Palavra-chave Principal' # ToDo 1
enableRobotsTXT: true
defaultContentLanguage: 'pt-br'
module:
  disable: true

# Configurações para Sitemap
sitemap:
  changefreq: 'weekly'
  priority: 0.8

# Variáveis do Produto
params: # ToDo 2
  logo: 'images/logo-produto.png'
  button_texto: 'Comprar'
  banner: 'images/banner-produto.png' # Caminho do banner do produto/criador
  titulo: 'Lance páginas de venda atrativas e ágeis.'
  subtitulo: "Torne-se um 'Gestor de Tráfego Esperto' e economize tempo e dinheiro com as suas campanhas de vendas. Aprenda a criar infinitas páginas de vendas com links atrativos tendo apenas um domínio."
  disclaimer:
    [
      '– Não é necessário saber programar.',
      '– Aprenda de forma simples com um Engenheiro de Software da PUCRS.',
      '– Receba essa linda template reutilizável imediatamente e aprenda a editá-la no curso.',
    ]
  cta_texto: 'Acessar Site Completo'
  cta_link: 'https://www.linkedin.com/in/jmfantin' # Link para o botão de CTA
